wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1714694191.798091
    t:
      1:
      - 50
      - 55
      2:
      - 50
      - 55
      3:
      - 23
      4: 3.9.15
      5: 0.13.9
      8:
      - 5
